import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "inverse-on-surface": "#303030",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#cfc2d6",
        "surface-container": "#1f1f1f",
        "on-secondary": "#002e6a",
        error: "#ffb4ab",
        "surface-variant": "#353535",
        "secondary-fixed": "#d8e2ff",
        "on-secondary-fixed-variant": "#004395",
        "secondary-container": "#0566d9",
        "tertiary-fixed-dim": "#4cd7f6",
        "surface-container-lowest": "#0e0e0e",
        primary: "#ddb7ff",
        outline: "#988d9f",
        "surface-tint": "#ddb7ff",
        "primary-fixed-dim": "#ddb7ff",
        "tertiary-container": "#009eb9",
        "surface-container-high": "#2a2a2a",
        tertiary: "#4cd7f6",
        "on-primary": "#490080",
        "on-primary-fixed": "#2c0051",
        "on-tertiary-container": "#002f38",
        "on-secondary-container": "#e6ecff",
        surface: "#131313",
        "on-tertiary-fixed": "#001f26",
        "surface-dim": "#131313",
        "outline-variant": "#4d4354",
        "surface-container-low": "#1b1b1b",
        "primary-fixed": "#f0dbff",
        "on-secondary-fixed": "#001a42",
        "error-container": "#93000a",
        "surface-container-highest": "#353535",
        "inverse-surface": "#e2e2e2",
        "inverse-primary": "#842bd2",
        "on-primary-container": "#400071",
        "tertiary-fixed": "#acedff",
        "primary-container": "#b76dff",
        "on-tertiary": "#003640",
        "surface-bright": "#393939",
        "on-tertiary-fixed-variant": "#004e5c",
        secondary: "#adc6ff",
        "on-primary-fixed-variant": "#6900b3",
        "secondary-fixed-dim": "#adc6ff",
        "on-surface": "#e2e2e2",
        "on-background": "#e2e2e2",
        background: "#131313",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.25rem",
        full: "9999px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "container-max": "1280px",
        unit: "8px",
        gutter: "24px",
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "display-xl": ["64px", { lineHeight: "72px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-xl-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
