export interface ToolFAQ {
  question: string;
  answer: string;
}

export interface Tool {
  slug: string;
  name: string;
  shortDescription: string;
  description: string;
  icon: string;
  iconColor: string;
  categorySlug: string;
  keywords: string[];
  faqs: ToolFAQ[];
  relatedSlugs: string[];
}

export interface ToolCategory {
  slug: string;
  name: string;
  description: string;
  icon: string;
  iconColor: string;
  bgColor: string;
}

export const categories: ToolCategory[] = [
  { slug: "ai-tools", name: "AI Tools", description: "Harness the power of artificial intelligence to write, translate, summarize, and build faster than ever before.", icon: "smart_toy", iconColor: "#ddb7ff", bgColor: "rgba(221,183,255,0.1)" },
  { slug: "pdf-tools", name: "PDF Tools", description: "Convert, merge, split, and compress PDF files with ease. No software installation required.", icon: "picture_as_pdf", iconColor: "#ffb4ab", bgColor: "rgba(255,180,171,0.1)" },
  { slug: "image-tools", name: "Image Tools", description: "Edit, resize, compress, and convert images instantly in your browser.", icon: "image", iconColor: "#4cd7f6", bgColor: "rgba(76,215,246,0.1)" },
  { slug: "developer-tools", name: "Developer Tools", description: "Format, encode, generate, and minify. Essential utilities for every developer's workflow.", icon: "terminal", iconColor: "#adc6ff", bgColor: "rgba(173,198,255,0.1)" },
  { slug: "calculators", name: "Calculators", description: "Generate passwords, QR codes, calculate BMI, age, word counts and more with precision.", icon: "calculate", iconColor: "#4cd7f6", bgColor: "rgba(76,215,246,0.1)" },
];

export const tools: Tool[] = [
  // AI Tools
  { slug: "ai-chat", name: "AI Chat", shortDescription: "Chat with a powerful AI assistant to get instant answers, brainstorm ideas, and solve problems.", description: "AI Chat gives you direct access to a state-of-the-art large language model. Ask questions, draft content, debug code, brainstorm ideas, or simply have a conversation. No account required — just start typing.", icon: "chat", iconColor: "#ddb7ff", categorySlug: "ai-tools", keywords: ["AI chat", "ChatGPT alternative", "AI assistant", "chatbot", "free AI chat"], faqs: [{ question: "Is AI Chat free to use?", answer: "Yes, ToolNest AI Chat is completely free with no account required. Simply open the tool and start chatting." }, { question: "What can I use AI Chat for?", answer: "You can use it to draft emails, answer questions, write code, summarize text, brainstorm ideas, translate content, and much more." }, { question: "Does AI Chat remember my previous conversations?", answer: "Conversations are session-based and are not stored permanently. Each new session starts fresh to protect your privacy." }, { question: "What AI model powers this tool?", answer: "AI Chat is powered by a leading large language model optimized for speed and accuracy on a wide range of tasks." }], relatedSlugs: ["ai-email-writer", "ai-text-summarizer", "ai-translator"] },
  { slug: "ai-resume-builder", name: "AI Resume Builder", shortDescription: "Create a professional, ATS-optimized resume in minutes using AI.", description: "The AI Resume Builder takes your experience and target role, then crafts a polished, ATS-friendly resume tailored to your industry. Generate bullet points, professional summaries, and skills sections — all optimized to get you past automated screening systems.", icon: "description", iconColor: "#ddb7ff", categorySlug: "ai-tools", keywords: ["AI resume builder", "resume generator", "ATS resume", "CV builder", "free resume maker"], faqs: [{ question: "Is the resume builder free?", answer: "Yes, the AI Resume Builder is completely free. Generate and download your resume with no hidden fees." }, { question: "What formats can I export my resume in?", answer: "You can export your resume as a PDF or Word document, ready to submit to employers." }, { question: "Will my resume pass ATS systems?", answer: "Yes, the AI optimizes your resume structure, keywords, and formatting to maximize ATS compatibility." }, { question: "Can I customize the AI-generated resume?", answer: "Absolutely. After the AI generates your resume, you can edit every section before downloading." }], relatedSlugs: ["ai-email-writer", "word-to-pdf", "ai-chat"] },
  { slug: "ai-email-writer", name: "AI Email Writer", shortDescription: "Write professional, persuasive emails in seconds with AI assistance.", description: "Stop staring at a blank screen. Describe the email you need — a follow-up, a cold outreach, a complaint, or a thank-you — and the AI Email Writer generates a polished draft instantly. Adjust tone, length, and style to match your voice.", icon: "mail", iconColor: "#ddb7ff", categorySlug: "ai-tools", keywords: ["AI email writer", "email generator", "professional email", "cold email writer", "email drafting tool"], faqs: [{ question: "What types of emails can the AI write?", answer: "Sales emails, follow-ups, apologies, thank-you notes, cold outreach, job applications, internal communications, and more." }, { question: "Can I choose the tone of the email?", answer: "Yes, you can specify the tone — formal, friendly, assertive, empathetic — and the AI will match it." }, { question: "Is there a character or word limit?", answer: "No strict limits. You can generate short emails or detailed long-form messages depending on your need." }, { question: "Can I rewrite or improve an existing email?", answer: "Yes, paste your draft and ask the AI to improve, shorten, or change the tone of your existing email." }], relatedSlugs: ["ai-chat", "ai-resume-builder", "ai-text-summarizer"] },
  { slug: "ai-translator", name: "AI Translator", shortDescription: "Translate text accurately between 100+ languages using AI.", description: "The AI Translator goes beyond word-for-word translation by understanding context, idioms, and tone. Support for 100+ languages with nuanced, natural-sounding output. Perfect for documents, emails, websites, and casual conversation.", icon: "translate", iconColor: "#ddb7ff", categorySlug: "ai-tools", keywords: ["AI translator", "online translator", "language translation", "translate text", "multilingual AI"], faqs: [{ question: "How many languages does the AI Translator support?", answer: "The translator supports over 100 languages, including all major world languages and many regional ones." }, { question: "Is the translation accurate?", answer: "The AI provides highly accurate, context-aware translations that preserve meaning, tone, and nuance — far beyond basic word substitution." }, { question: "Can I translate documents or only short text?", answer: "Both. Paste short phrases or paste entire paragraphs. Document translation support is coming soon." }, { question: "Is the AI Translator free?", answer: "Yes, completely free with no usage limits for standard translations." }], relatedSlugs: ["ai-chat", "ai-text-summarizer", "ai-email-writer"] },
  { slug: "ai-text-summarizer", name: "AI Text Summarizer", shortDescription: "Summarize long articles, documents, and text into concise key points instantly.", description: "Paste any long-form content — articles, research papers, reports, or web pages — and get a clear, accurate summary in seconds. Choose your preferred output length and format: bullet points, paragraph, or executive summary.", icon: "summarize", iconColor: "#ddb7ff", categorySlug: "ai-tools", keywords: ["AI text summarizer", "article summarizer", "text summary generator", "summarize document", "AI summary tool"], faqs: [{ question: "What types of content can I summarize?", answer: "Articles, blog posts, research papers, PDFs (pasted text), reports, emails, meeting notes, and any long-form text." }, { question: "Can I choose how long the summary is?", answer: "Yes. You can choose a brief 3-line summary, a structured bullet-point list, or a detailed paragraph summary." }, { question: "Does the summarizer preserve key facts and data?", answer: "Yes, the AI is specifically tuned to retain critical information, statistics, and key arguments while cutting filler content." }, { question: "Is there a word limit on what I can summarize?", answer: "The tool supports up to several thousand words in a single request — enough for most articles and reports." }], relatedSlugs: ["ai-chat", "ai-translator", "word-counter"] },
  // PDF Tools
  { slug: "pdf-to-word", name: "PDF to Word", shortDescription: "Convert PDF files to editable Word documents instantly.", description: "Transform any PDF into a fully editable .docx Word document while preserving formatting, tables, and images. Perfect for editing scanned documents, contracts, and reports without retyping a single word.", icon: "picture_as_pdf", iconColor: "#ffb4ab", categorySlug: "pdf-tools", keywords: ["PDF to Word", "convert PDF to Word", "PDF to DOCX", "editable PDF converter", "free PDF converter"], faqs: [{ question: "Will the formatting be preserved?", answer: "Yes, the converter maintains fonts, tables, columns, images, and layout as closely as possible to the original PDF." }, { question: "Does it work with scanned PDFs?", answer: "Yes, OCR (optical character recognition) is applied to scanned documents to extract and convert text accurately." }, { question: "Is there a file size limit?", answer: "Files up to 50MB are supported. For larger files, consider compressing the PDF first using our Compress PDF tool." }, { question: "Is the converted file editable in Microsoft Word?", answer: "Yes, the output is a standard .docx file compatible with Microsoft Word, Google Docs, and LibreOffice." }], relatedSlugs: ["word-to-pdf", "merge-pdf", "compress-pdf"] },
  { slug: "word-to-pdf", name: "Word to PDF", shortDescription: "Convert Word documents to PDF with perfect formatting preservation.", description: "Convert .doc and .docx files to PDF format instantly. The output is pixel-perfect — fonts, spacing, images, and page layout are preserved exactly as they appear in Word.", icon: "description", iconColor: "#ffb4ab", categorySlug: "pdf-tools", keywords: ["Word to PDF", "convert Word to PDF", "DOCX to PDF", "document converter", "free Word converter"], faqs: [{ question: "Will images and tables look the same in the PDF?", answer: "Yes. The converter renders your Word document exactly as it would print, preserving all embedded images, tables, and formatting." }, { question: "Does it support both .doc and .docx formats?", answer: "Yes, both legacy .doc and modern .docx formats are fully supported." }, { question: "Can I convert password-protected Word files?", answer: "You'll need to remove the password protection from the document before uploading it for conversion." }, { question: "Is the conversion instant?", answer: "Most documents convert in under 10 seconds. Larger, image-heavy documents may take slightly longer." }], relatedSlugs: ["pdf-to-word", "compress-pdf", "split-pdf"] },
  { slug: "merge-pdf", name: "Merge PDF", shortDescription: "Combine multiple PDF files into a single document in seconds.", description: "Upload two or more PDF files, drag to reorder them, and merge into a single polished PDF. Perfect for combining reports, contracts, presentations, or chapters into one unified document.", icon: "merge", iconColor: "#ffb4ab", categorySlug: "pdf-tools", keywords: ["merge PDF", "combine PDF", "join PDF files", "PDF merger", "free PDF merge tool"], faqs: [{ question: "How many PDFs can I merge at once?", answer: "You can merge up to 20 PDF files in a single operation." }, { question: "Can I reorder pages before merging?", answer: "Yes, you can drag and drop the uploaded PDFs to set the order before merging." }, { question: "Will the quality of the PDFs be affected?", answer: "No. The merge process is lossless — all content, fonts, and images remain at original quality." }, { question: "Is there a file size limit per document?", answer: "Each individual PDF can be up to 50MB. The total combined size should not exceed 200MB." }], relatedSlugs: ["split-pdf", "compress-pdf", "pdf-to-word"] },
  { slug: "split-pdf", name: "Split PDF", shortDescription: "Split a PDF into separate pages or custom page ranges.", description: "Extract specific pages or divide a large PDF into smaller sections. Choose to split by every page, by custom page ranges, or extract individual pages. Downloads as individual files or a ZIP archive.", icon: "call_split", iconColor: "#ffb4ab", categorySlug: "pdf-tools", keywords: ["split PDF", "extract PDF pages", "divide PDF", "PDF splitter", "free PDF split tool"], faqs: [{ question: "Can I extract only specific pages from a PDF?", answer: "Yes. Specify individual pages (e.g., 1, 3, 5) or ranges (e.g., 1-5, 8-12) to extract exactly what you need." }, { question: "How will I receive the split files?", answer: "Split files can be downloaded individually or as a single ZIP archive containing all the extracted pages." }, { question: "Will the content quality be preserved?", answer: "Yes, splitting is a lossless operation. All text, images, and formatting remain at original quality." }, { question: "Is there a page count limit?", answer: "The tool supports PDFs with up to 500 pages." }], relatedSlugs: ["merge-pdf", "compress-pdf", "pdf-to-word"] },
  { slug: "image-to-pdf", name: "Image to PDF", shortDescription: "Convert JPG, PNG and WEBP images into a professional PDF document.", description: "Upload one or more images and convert them into a polished PDF document in seconds. Supports JPG, JPEG, PNG and WebP. Choose page size, orientation, margins and layout — one image per page or a grid. Drag to reorder pages and rotate individual images before converting.", icon: "image", iconColor: "#ffb4ab", categorySlug: "pdf-tools", keywords: ["image to PDF", "JPG to PDF", "PNG to PDF", "convert image to PDF", "photo to PDF", "pictures to PDF"], faqs: [{ question: "What image formats are supported?", answer: "JPG, JPEG, PNG and WebP images are all supported. The tool processes everything entirely in your browser — no files are uploaded to any server." }, { question: "Can I control the order of images in the PDF?", answer: "Yes. You can upload up to 50 images, drag to reorder them, and rotate each one independently before generating the PDF." }, { question: "Will my images lose quality when converted to PDF?", answer: "JPEG and PNG images are embedded at their original quality. WebP images are converted to high-quality JPEG internally to ensure full PDF compatibility." }, { question: "Is there a file size limit per image?", answer: "Each image can be up to 20 MB. Everything is processed locally in your browser, so there are no server-side size restrictions." }], relatedSlugs: ["merge-pdf", "compress-pdf", "jpg-to-png"] },
  { slug: "compress-pdf", name: "Compress PDF", shortDescription: "Reduce PDF file size without compromising quality.", description: "Shrink large PDF files for easy sharing via email, upload, or cloud storage. Choose from three compression levels — light, balanced, and maximum — to find the perfect balance between file size and quality.", icon: "compress", iconColor: "#ffb4ab", categorySlug: "pdf-tools", keywords: ["compress PDF", "reduce PDF size", "PDF compressor", "shrink PDF", "free PDF compression"], faqs: [{ question: "How much can the file size be reduced?", answer: "Depending on content, you can typically reduce file size by 50–90%. Image-heavy PDFs compress the most." }, { question: "Will compression affect text readability?", answer: "No. Text is never degraded during compression. Only image DPI and embedded resource quality may be adjusted." }, { question: "What compression levels are available?", answer: "Three levels: Light (minimal quality loss), Balanced (recommended), and Maximum (smallest size, some visible quality reduction in images)." }, { question: "Can I compress a password-protected PDF?", answer: "No, password protection must be removed before compression. The output file will not be password protected." }], relatedSlugs: ["merge-pdf", "split-pdf", "pdf-to-word"] },
  // Image Tools
  { slug: "remove-background", name: "Remove Background", shortDescription: "Instantly remove image backgrounds with AI — no manual editing needed.", description: "Upload any photo and AI automatically detects and removes the background in seconds. Perfect for product photos, profile pictures, and creative projects. Download with a transparent PNG background, ready for any use.", icon: "auto_fix_high", iconColor: "#4cd7f6", categorySlug: "image-tools", keywords: ["remove background", "background remover", "transparent background", "AI background removal", "free background eraser"], faqs: [{ question: "What image formats are supported?", answer: "JPG, PNG, WEBP, and BMP are supported for input. Output is always a transparent PNG." }, { question: "Does it work on complex backgrounds?", answer: "Yes, the AI handles complex backgrounds including busy scenes, gradients, and multi-colored environments." }, { question: "Is there a maximum image size?", answer: "Images up to 25MB and 5000×5000 pixels are supported." }, { question: "Can I use the result commercially?", answer: "Yes, you own all rights to your processed images. There are no usage restrictions on outputs." }], relatedSlugs: ["image-resizer", "image-compressor", "jpg-to-png"] },
  { slug: "image-resizer", name: "Image Resizer", shortDescription: "Resize images to exact dimensions or percentages instantly.", description: "Resize any image to exact pixel dimensions or scale by percentage while maintaining or adjusting aspect ratio. Supports bulk resizing and common preset sizes for social media, web, and print.", icon: "photo_size_select_large", iconColor: "#4cd7f6", categorySlug: "image-tools", keywords: ["image resizer", "resize image online", "photo resizer", "change image size", "free image resize tool"], faqs: [{ question: "Can I resize without distorting the image?", answer: "Yes, you can lock the aspect ratio to resize proportionally, or unlock it for custom dimensions." }, { question: "What preset sizes are available?", answer: "Common presets include Instagram post, Twitter banner, LinkedIn profile, YouTube thumbnail, A4 print, and more." }, { question: "Can I resize multiple images at once?", answer: "Yes, batch resize is supported. Upload multiple images and apply the same dimensions to all." }, { question: "What output formats are available?", answer: "You can output as JPG, PNG, or WEBP, with optional quality control for JPG and WEBP." }], relatedSlugs: ["remove-background", "image-compressor", "webp-converter"] },
  { slug: "image-compressor", name: "Image Compressor", shortDescription: "Compress images to reduce file size without visible quality loss.", description: "Reduce image file sizes for faster web pages, email attachments, and cloud storage. The smart compression algorithm removes redundant data while preserving visual quality. Supports JPG, PNG, and WEBP.", icon: "compress", iconColor: "#4cd7f6", categorySlug: "image-tools", keywords: ["image compressor", "compress image online", "reduce image size", "JPG compressor", "PNG optimizer"], faqs: [{ question: "How much can images be compressed?", answer: "Typically 40–80% size reduction with no perceptible quality loss. Results vary by image type and content." }, { question: "Does compression affect image dimensions?", answer: "No. Compression only reduces file size — the pixel dimensions remain unchanged." }, { question: "Can I compress multiple images at once?", answer: "Yes, upload up to 20 images and compress them all in a single batch operation." }, { question: "What is the maximum file size for upload?", answer: "Each image can be up to 20MB before compression." }], relatedSlugs: ["image-resizer", "remove-background", "webp-converter"] },
  { slug: "jpg-to-png", name: "JPG to PNG", shortDescription: "Convert JPG images to PNG format with transparent background support.", description: "Convert JPG and JPEG files to PNG format instantly. PNG supports lossless compression and transparency, making it ideal for logos, icons, and graphics where quality and sharp edges matter.", icon: "image", iconColor: "#4cd7f6", categorySlug: "image-tools", keywords: ["JPG to PNG", "JPEG to PNG converter", "convert JPG to PNG", "image format converter", "free JPG PNG conversion"], faqs: [{ question: "Will converting JPG to PNG improve quality?", answer: "PNG is lossless, so the conversion preserves all quality from the JPG. However, it won't recover quality already lost during JPG compression." }, { question: "Can I convert multiple files at once?", answer: "Yes, batch conversion is supported — upload multiple JPG files and convert them all at once." }, { question: "Will the PNG file be larger than the JPG?", answer: "Usually yes, because PNG is lossless. If file size is a concern, consider using our Image Compressor after conversion." }, { question: "Is there a file size limit?", answer: "Individual files up to 20MB are supported." }], relatedSlugs: ["webp-converter", "image-compressor", "image-resizer"] },
  { slug: "webp-converter", name: "WebP Converter", shortDescription: "Convert images to and from WebP format for optimal web performance.", description: "Convert JPG, PNG, and GIF files to WebP for up to 30% smaller file sizes — and convert WebP back to JPG or PNG for compatibility. Essential for web developers optimizing Core Web Vitals and page load speeds.", icon: "swap_horiz", iconColor: "#4cd7f6", categorySlug: "image-tools", keywords: ["WebP converter", "convert to WebP", "WebP to JPG", "WebP to PNG", "image format converter"], faqs: [{ question: "Why should I use WebP instead of JPG or PNG?", answer: "WebP images are typically 25–34% smaller than equivalent JPG files and 26% smaller than PNG, with comparable or better quality." }, { question: "Can I convert WebP back to JPG or PNG?", answer: "Yes, two-way conversion is supported — WebP to JPG, WebP to PNG, and vice versa." }, { question: "Does WebP support transparency?", answer: "Yes, WebP supports transparency (alpha channel) just like PNG, but with much smaller file sizes." }, { question: "Is WebP supported in all browsers?", answer: "WebP is supported by all modern browsers including Chrome, Firefox, Safari (v14+), and Edge." }], relatedSlugs: ["jpg-to-png", "image-compressor", "image-resizer"] },
  // Developer Tools
  { slug: "json-formatter", name: "JSON Formatter", shortDescription: "Format, validate, and beautify JSON data instantly.", description: "Paste raw or minified JSON and instantly get a beautifully formatted, syntax-highlighted, and validated output. Identify syntax errors, collapse nodes, and copy the cleaned result in one click.", icon: "data_object", iconColor: "#adc6ff", categorySlug: "developer-tools", keywords: ["JSON formatter", "JSON beautifier", "JSON validator", "format JSON online", "JSON pretty print"], faqs: [{ question: "Does the JSON Formatter validate my JSON?", answer: "Yes, it validates the JSON structure and highlights syntax errors with the exact line and character position." }, { question: "Can I collapse and expand JSON nodes?", answer: "Yes, the tree view allows you to collapse and expand objects and arrays for easier navigation of large payloads." }, { question: "Is my JSON data stored on your servers?", answer: "No. All processing happens entirely in your browser. Your data is never sent to or stored on any server." }, { question: "Can I minify JSON as well?", answer: "Yes, in addition to formatting, you can minify JSON to remove all whitespace for compact output." }], relatedSlugs: ["base64-encoder", "html-minifier", "css-minifier"] },
  { slug: "base64-encoder", name: "Base64 Encoder", shortDescription: "Encode and decode Base64 strings and files instantly.", description: "Encode plain text, URLs, or binary files to Base64 format — and decode Base64 strings back to their original form. Supports file encoding for embedding images in HTML/CSS and encoding API payloads.", icon: "code", iconColor: "#adc6ff", categorySlug: "developer-tools", keywords: ["Base64 encoder", "Base64 decoder", "encode Base64", "decode Base64", "Base64 converter online"], faqs: [{ question: "What is Base64 encoding used for?", answer: "Base64 is used to encode binary data (like images) for embedding in HTML/CSS, transmitting over text-based protocols, and API authentication headers." }, { question: "Can I encode files, not just text?", answer: "Yes, you can upload any file and encode it to Base64. Common uses include embedding images as data URIs." }, { question: "Is there a size limit for encoding?", answer: "Text encoding has no practical limit. File encoding supports files up to 5MB." }, { question: "Is my data processed securely?", answer: "All encoding and decoding is done client-side in your browser. Nothing is sent to our servers." }], relatedSlugs: ["json-formatter", "uuid-generator", "html-minifier"] },
  { slug: "uuid-generator", name: "UUID Generator", shortDescription: "Generate single or bulk UUIDs (v1, v4) instantly.", description: "Generate cryptographically random UUID v4 or time-based UUID v1 identifiers instantly. Generate one or thousands in a batch, copy individually or all at once. Essential for database primary keys, API tokens, and unique identifiers.", icon: "fingerprint", iconColor: "#adc6ff", categorySlug: "developer-tools", keywords: ["UUID generator", "GUID generator", "generate UUID", "UUID v4", "unique ID generator"], faqs: [{ question: "What is the difference between UUID v1 and v4?", answer: "UUID v1 is time-based and includes a timestamp and machine identifier. UUID v4 is randomly generated and is more commonly used for privacy and security." }, { question: "Are the generated UUIDs truly unique?", answer: "UUID v4 uses cryptographic randomness, making collisions astronomically unlikely — effectively guaranteed unique for any practical use case." }, { question: "Can I generate multiple UUIDs at once?", answer: "Yes, you can generate anywhere from 1 to 10,000 UUIDs in a single batch and export them as a text file." }, { question: "Can I use these UUIDs in production?", answer: "Yes, they are production-grade identifiers suitable for database primary keys, session tokens, file names, and any unique identifier need." }], relatedSlugs: ["base64-encoder", "json-formatter", "password-generator"] },
  { slug: "html-minifier", name: "HTML Minifier", shortDescription: "Minify HTML to reduce file size and improve page load speed.", description: "Remove unnecessary whitespace, comments, and redundant attributes from HTML files to reduce their size by up to 30%. Faster HTML delivery improves page load times and Core Web Vitals scores without changing functionality.", icon: "html", iconColor: "#adc6ff", categorySlug: "developer-tools", keywords: ["HTML minifier", "minify HTML", "HTML compressor", "reduce HTML size", "HTML optimizer"], faqs: [{ question: "Will minifying HTML break my website?", answer: "No, when done correctly. The minifier only removes whitespace and comments — it does not alter element structure, attributes, or JavaScript." }, { question: "Does it minify inline CSS and JavaScript?", answer: "Yes, the advanced mode also minifies inline style blocks and script blocks within the HTML." }, { question: "How much size reduction can I expect?", answer: "Typically 10–30% for standard HTML, up to 40% for heavily commented or whitespace-rich templates." }, { question: "Can I beautify (unminify) HTML too?", answer: "Yes, the tool works both ways — paste minified HTML to format and beautify it for readability." }], relatedSlugs: ["css-minifier", "json-formatter", "base64-encoder"] },
  { slug: "css-minifier", name: "CSS Minifier", shortDescription: "Minify CSS to reduce stylesheet size and boost website performance.", description: "Strip whitespace, comments, and redundant code from CSS files to produce a compact, production-ready stylesheet. Smaller CSS means faster parse times and improved Lighthouse scores for your web projects.", icon: "css", iconColor: "#adc6ff", categorySlug: "developer-tools", keywords: ["CSS minifier", "minify CSS", "CSS compressor", "reduce CSS size", "CSS optimizer"], faqs: [{ question: "Will minifying CSS affect how my website looks?", answer: "No. Minification only removes whitespace and comments. All CSS rules, selectors, and properties remain intact." }, { question: "Does it handle vendor prefixes?", answer: "Yes, vendor prefixes (-webkit-, -moz-, etc.) are preserved exactly as-is during minification." }, { question: "Can I also beautify CSS?", answer: "Yes, paste minified CSS to auto-format and indent it for readable, maintainable code." }, { question: "Is it safe to use the minified CSS directly in production?", answer: "Absolutely. The output is production-ready. We recommend keeping your original unminified version for development." }], relatedSlugs: ["html-minifier", "json-formatter", "base64-encoder"] },
  // Calculators
  { slug: "password-generator", name: "Password Generator", shortDescription: "Generate strong, secure, random passwords instantly.", description: "Create cryptographically secure passwords of any length with customizable character sets — uppercase, lowercase, numbers, and symbols. Generate single passwords or bulk sets, with a real-time strength indicator.", icon: "lock", iconColor: "#4cd7f6", categorySlug: "calculators", keywords: ["password generator", "strong password generator", "random password", "secure password maker", "free password generator"], faqs: [{ question: "Are the generated passwords truly random?", answer: "Yes, passwords are generated using the browser's cryptographic random number generator (Web Crypto API), making them highly secure and unpredictable." }, { question: "What is the recommended password length?", answer: "We recommend at least 16 characters for important accounts. Use 20+ characters with symbols for maximum security." }, { question: "Are my generated passwords stored?", answer: "No. All generation happens locally in your browser. We never see, transmit, or store any generated passwords." }, { question: "Can I generate multiple passwords at once?", answer: "Yes, generate up to 100 passwords in a batch and copy or export them all at once." }], relatedSlugs: ["uuid-generator", "qr-code-generator", "word-counter"] },
  { slug: "qr-code-generator", name: "QR Code Generator", shortDescription: "Generate QR codes for URLs, text, contacts, and more.", description: "Create custom QR codes for any URL, plain text, email, phone number, Wi-Fi credentials, or vCard contact. Customize size and download as PNG or SVG for print and digital use.", icon: "qr_code", iconColor: "#4cd7f6", categorySlug: "calculators", keywords: ["QR code generator", "create QR code", "free QR generator", "custom QR code", "QR code maker"], faqs: [{ question: "What types of data can a QR code contain?", answer: "URLs, plain text, email addresses, phone numbers, SMS messages, Wi-Fi login credentials, and vCard contacts." }, { question: "What download formats are available?", answer: "PNG (for digital use) and SVG (for scalable print use). SVG is recommended for large-format printing." }, { question: "Do the QR codes expire?", answer: "No. QR codes generated with ToolNest are static and do not expire. As long as the destination URL is live, the QR code works." }, { question: "Can I customize the QR code appearance?", answer: "Yes, you can customize the size and — coming soon — colors and embedded logos." }], relatedSlugs: ["password-generator", "word-counter", "bmi-calculator"] },
  { slug: "bmi-calculator", name: "BMI Calculator", shortDescription: "Calculate your Body Mass Index and understand your health category.", description: "Enter your height and weight to instantly calculate your BMI. Results include your BMI value, health category (Underweight, Normal, Overweight, Obese), and context for what the number means for your health.", icon: "monitor_weight", iconColor: "#4cd7f6", categorySlug: "calculators", keywords: ["BMI calculator", "body mass index", "calculate BMI", "BMI chart", "free health calculator"], faqs: [{ question: "What is a healthy BMI range?", answer: "A BMI between 18.5 and 24.9 is considered normal/healthy. Under 18.5 is underweight, 25–29.9 is overweight, and 30+ is considered obese." }, { question: "Does the BMI calculator support both metric and imperial units?", answer: "Yes, you can enter height and weight in either metric (cm/kg) or imperial (ft/in/lbs) units." }, { question: "Is BMI an accurate measure of health?", answer: "BMI is a useful screening tool but has limitations — it does not account for muscle mass, bone density, or fat distribution. Consult a healthcare provider for a full health assessment." }, { question: "Is my data stored or shared?", answer: "No. All calculations happen locally in your browser. No personal health data is ever sent to our servers." }], relatedSlugs: ["age-calculator", "word-counter", "qr-code-generator"] },
  { slug: "age-calculator", name: "Age Calculator", shortDescription: "Calculate your exact age in years, months, days, hours, and minutes.", description: "Enter your date of birth and get your exact age broken down into years, months, days, hours, and even minutes. Also shows the date of your next birthday and how many days until it arrives.", icon: "cake", iconColor: "#4cd7f6", categorySlug: "calculators", keywords: ["age calculator", "calculate age", "how old am I", "birthday calculator", "exact age calculator"], faqs: [{ question: "How precise is the age calculation?", answer: "The calculator is precise to the day, and optionally shows hours and minutes based on a specific birth time." }, { question: "Can I calculate the age for any date, not just today?", answer: "Yes, you can set a custom target date to calculate age at any specific point in time." }, { question: "Does it account for leap years?", answer: "Yes, leap years are fully accounted for in all calculations." }, { question: "Can I calculate the age difference between two people?", answer: "Yes, the tool includes an age difference mode where you enter two dates and get the exact difference." }], relatedSlugs: ["bmi-calculator", "word-counter", "qr-code-generator"] },
  { slug: "word-counter", name: "Word Counter", shortDescription: "Count words, characters, sentences, paragraphs, and reading time instantly.", description: "Paste or type your text to get instant statistics: word count, character count (with and without spaces), sentence count, paragraph count, and estimated reading time. Perfect for essays, articles, and social media posts.", icon: "spellcheck", iconColor: "#4cd7f6", categorySlug: "calculators", keywords: ["word counter", "character counter", "count words online", "text statistics", "word count tool"], faqs: [{ question: "Does the word counter work in real time?", answer: "Yes, statistics update instantly as you type or paste text — no button click required." }, { question: "How is reading time calculated?", answer: "Reading time is estimated based on an average reading speed of 200–250 words per minute for adults." }, { question: "Does it count characters with or without spaces?", answer: "Both. The tool shows character count with spaces and without spaces as separate values." }, { question: "Can I use this for checking social media character limits?", answer: "Yes, the character counter is ideal for Twitter (280), LinkedIn posts, meta descriptions (155), and other character-limited platforms." }], relatedSlugs: ["ai-text-summarizer", "age-calculator", "bmi-calculator"] },
];

export function getCategoryBySlug(slug: string): ToolCategory | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(categorySlug: string): Tool[] {
  return tools.filter((t) => t.categorySlug === categorySlug);
}

export function getRelatedTools(slugs: string[]): Tool[] {
  return slugs.map((slug) => getToolBySlug(slug)).filter((t): t is Tool => t !== undefined);
}
